# Generated by Django 5.0.2 on 2026-08-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_product_product_type_has_matching_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(limit_choices_to={'product_type__in': ['nutrition_plan', 'exercise_plan']}, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('start_offset_days', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('recurrence_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_count', models.PositiveIntegerField(blank=True, null=True)),
                ('linked_products', models.ManyToManyField(blank=True, related_name='plan_events', to='ecommerce.product')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plans.plan')),
            ],
            options={
                'ordering': ['start_offset_days', 'id'],
            },
        ),
    ]
