# Generated by Django 5.0.2 on 2026-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('nutrition_plan', 'Nutrition plan'), ('exercise_plan', 'Exercise plan'), ('nutrition_product', 'Nutrition product'), ('exercise_product', 'Exercise product')], default='exercise_product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price for nutrition and exercise plans.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-off price for nutrition and exercise products.', max_digits=10, null=True),
        ),
    ]
