# Generated by Django 5.0.2 on 2026-08-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_product_type_product_subscription_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('price__isnull', True), ('product_type__in', ['nutrition_plan', 'exercise_plan']), ('subscription_price__isnull', False)), models.Q(('price__isnull', False), ('product_type__in', ['nutrition_product', 'exercise_product']), ('subscription_price__isnull', True)), _connector='OR'), name='product_type_has_matching_price'),
        ),
    ]
