# Generated by Django 5.0.2 on 2026-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
