# Generated by Django 5.0.2 on 2026-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_status',
            field=models.CharField(blank=True, help_text='The last status reported by Stripe.', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='canceled', max_length=20),
        ),
    ]
